version: "3.9"
services:
  db:
    build:
      context: db
    image: filiptepes/rms-db
    container_name: rms-db
    restart: always
    ports:
      - "5432:5432"
      - "5433:5433"
  backend:
    build:
      context: backend
    image: filiptepes/rms-backend
    container_name: "rms-backend"
    restart: always
    ports:
      - "3000:3000"
    volumes:
        - ./backend:/app
